baseURL = 'https://code.pyjamacafe.com'
languageCode = 'en-us'
title = 'Code.PyjamaCafe'
theme = 'pyjamacode'

[params]
  author = 'Typobrahe Education LLP'
  description = 'A coding platform for embedded systems software and firmware development.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

  [markup.highlight]
    style = 'github'
    noClasses = true
    codeFences = true

disableKinds = ['taxonomy', 'term']

[taxonomies]

[outputs]
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']

