baseURL = ''
languageCode = 'en-us'
title = 'Code @ Pyjama Cafe'
theme = 'pyjamacode'

[params]
  author = 'Team Pyjama Cafe'
  description = 'A coding platform for embedded systems software and firmware development.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

disableKinds = ['taxonomy', 'term']

[taxonomies]

[outputs]
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']

